# Generated by Django 4.0 on 2021-12-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(max_length=100, verbose_name="So'zlar")),
                ('gender', models.CharField(choices=[('der', 'Der'), ('die', 'Die'), ('das', 'Das')], max_length=3, verbose_name='Rot')),
            ],
        ),
    ]
